### PR TITLE
Migrated to AndroidX

### PR DESCRIPTION
**Pull request by balajisunku-halodoc**

### CODE REVIEW

**Review by orhanobut — APPROVED** [review]
Looks good to me, thanks for the contribution

**Comment by wangmir** [comment]
how can we use this version at import situation..? Is this version is released?

**Comment by sergeys-opera** [comment]
@orhanobut any chance that you can release a new version of the lib including this fix?

**Comment by sergeys-opera** [comment]
As a temporary workaround old Android libraries can be excluded explicitly in the logger dependency declaration:
```gradle
    implementation (libs.orhanobut.logger) {
        // Annotations are not used at runtime and can safely be excluded in order to disable the jetifier.
        exclude group: 'com.android.support', module: 'support-annotations'
    }
```

**Comment by artemyto** [comment]
Another way is to use jitpack.io to add dependency to master snapshot: https://jitpack.io/#orhanobut/logger/master-SNAPSHOT

**Pull request merged**
